-- Kontakte (Kunden, Lieferanten, Firmen, Personen)
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS dg_contacts (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    login VARCHAR(60) NOT NULL,
    salutation VARCHAR(20) NOT NULL DEFAULT '',
    first_name VARCHAR(100) NOT NULL DEFAULT '',
    last_name VARCHAR(100) NOT NULL DEFAULT '',
    display_name VARCHAR(191) NOT NULL DEFAULT '',
    company_name VARCHAR(191) NOT NULL DEFAULT '',
    email VARCHAR(191) NOT NULL DEFAULT '',
    email_2 VARCHAR(191) NOT NULL DEFAULT '',
    phone_1 VARCHAR(50) NOT NULL DEFAULT '',
    phone_2 VARCHAR(50) NOT NULL DEFAULT '',
    customer_number VARCHAR(50) NOT NULL DEFAULT '',
    supplier_number VARCHAR(50) NOT NULL DEFAULT '',
    tax_number VARCHAR(50) NOT NULL DEFAULT '',
    vat_id VARCHAR(50) NOT NULL DEFAULT '',
    contact_note TEXT NULL,
    address1_extra VARCHAR(191) NOT NULL DEFAULT '',
    address1_street VARCHAR(191) NOT NULL DEFAULT '',
    address1_postal VARCHAR(20) NOT NULL DEFAULT '',
    address1_city VARCHAR(100) NOT NULL DEFAULT '',
    address1_country CHAR(2) NOT NULL DEFAULT 'DE',
    address2_extra VARCHAR(191) NOT NULL DEFAULT '',
    address2_street VARCHAR(191) NOT NULL DEFAULT '',
    address2_postal VARCHAR(20) NOT NULL DEFAULT '',
    address2_city VARCHAR(100) NOT NULL DEFAULT '',
    address2_country CHAR(2) NOT NULL DEFAULT 'DE',
    website VARCHAR(255) NOT NULL DEFAULT '',
    contact_role VARCHAR(50) NOT NULL DEFAULT 'kunde',
    contact_persons JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY login (login),
    KEY idx_display_name (display_name),
    KEY idx_company_name (company_name),
    KEY idx_customer_number (customer_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
